version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "server"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      server-dev-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      server-prod-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "client"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    groups:
      client-dev-minor-patch:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      client-prod-minor-patch:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "chore(ci)"
